# pull official base image
FROM python:3.9.1-slim-buster

# set work directory
WORKDIR /usr/src/app

# install operating dependencies
RUN apt-get -y update \
    && apt-get -y install \
    g++\
    gcc \
    libpq-dev \
    netcat

# install python packages
RUN pip install --upgrade pip \
    && pip install --upgrade wheel
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

#copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

#setting file permissions
RUN chmod 700 /usr/src/app/entrypoint.sh

# copy project
COPY . /usr/src/app/

# run entrypoint.sh
ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
