"""empty message

Revision ID: 2fe6090632f2
Revises: a1a2e3d05d0e
Create Date: 2021-01-07 21:55:31.573518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe6090632f2'
down_revision = 'a1a2e3d05d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'nickname')
    # ### end Alembic commands ###
