"""empty message

Revision ID: a1a2e3d05d0e
Revises: 1a37d84a2371
Create Date: 2020-12-31 21:47:56.490438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a2e3d05d0e'
down_revision = '1a37d84a2371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'active')
    # ### end Alembic commands ###
