"""empty message
Revision ID: dfdb09aee68a
Revises: 3ae558098c29
Create Date: 2020-11-22 20:10:26.774795
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfdb09aee68a'
down_revision = '3ae558098c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('campaign_name', 'worlds', ['name', 'campaign_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_name', 'worlds', type_='unique')
    # ### end Alembic commands ###